cassandra:
  hosts:
    - "188.242.205.5"
  keyspace: "chaika_sales"
  user: "grisha"
  password: "n*_irR#2*$h_341nUe"

cassandra-test:
  hosts:
    - "188.242.205.5"
  keyspace: "chaika_sales_test"
  user: "grisha"
  password: "n*_irR#2*$h_341nUe"