// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: rprts/chaika_reports.proto

// pick a proto package name that makes sense for your reports

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Year          string                 `protobuf:"bytes,2,opt,name=year,proto3" json:"year,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripRequest) Reset() {
	*x = GetTripRequest{}
	mi := &file_rprts_chaika_reports_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripRequest) ProtoMessage() {}

func (x *GetTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rprts_chaika_reports_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripRequest.ProtoReflect.Descriptor instead.
func (*GetTripRequest) Descriptor() ([]byte, []int) {
	return file_rprts_chaika_reports_proto_rawDescGZIP(), []int{0}
}

func (x *GetTripRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *GetTripRequest) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *GetTripRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

type GetTripReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trip          *Trip                  `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripReply) Reset() {
	*x = GetTripReply{}
	mi := &file_rprts_chaika_reports_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripReply) ProtoMessage() {}

func (x *GetTripReply) ProtoReflect() protoreflect.Message {
	mi := &file_rprts_chaika_reports_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripReply.ProtoReflect.Descriptor instead.
func (*GetTripReply) Descriptor() ([]byte, []int) {
	return file_rprts_chaika_reports_proto_rawDescGZIP(), []int{1}
}

func (x *GetTripReply) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

type Trip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Carriage      []*Carriage            `protobuf:"bytes,1,rep,name=carriage,proto3" json:"carriage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trip) Reset() {
	*x = Trip{}
	mi := &file_rprts_chaika_reports_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trip) ProtoMessage() {}

func (x *Trip) ProtoReflect() protoreflect.Message {
	mi := &file_rprts_chaika_reports_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trip.ProtoReflect.Descriptor instead.
func (*Trip) Descriptor() ([]byte, []int) {
	return file_rprts_chaika_reports_proto_rawDescGZIP(), []int{2}
}

func (x *Trip) GetCarriage() []*Carriage {
	if x != nil {
		return x.Carriage
	}
	return nil
}

type Carriage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        *TripID                `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CarriageId    int32                  `protobuf:"varint,3,opt,name=carriage_id,json=carriageId,proto3" json:"carriage_id,omitempty"`
	Carts         []*Cart                `protobuf:"bytes,4,rep,name=carts,proto3" json:"carts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Carriage) Reset() {
	*x = Carriage{}
	mi := &file_rprts_chaika_reports_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Carriage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Carriage) ProtoMessage() {}

func (x *Carriage) ProtoReflect() protoreflect.Message {
	mi := &file_rprts_chaika_reports_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Carriage.ProtoReflect.Descriptor instead.
func (*Carriage) Descriptor() ([]byte, []int) {
	return file_rprts_chaika_reports_proto_rawDescGZIP(), []int{3}
}

func (x *Carriage) GetTripId() *TripID {
	if x != nil {
		return x.TripId
	}
	return nil
}

func (x *Carriage) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Carriage) GetCarriageId() int32 {
	if x != nil {
		return x.CarriageId
	}
	return 0
}

func (x *Carriage) GetCarts() []*Cart {
	if x != nil {
		return x.Carts
	}
	return nil
}

type TripID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Year          string                 `protobuf:"bytes,2,opt,name=year,proto3" json:"year,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripID) Reset() {
	*x = TripID{}
	mi := &file_rprts_chaika_reports_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripID) ProtoMessage() {}

func (x *TripID) ProtoReflect() protoreflect.Message {
	mi := &file_rprts_chaika_reports_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripID.ProtoReflect.Descriptor instead.
func (*TripID) Descriptor() ([]byte, []int) {
	return file_rprts_chaika_reports_proto_rawDescGZIP(), []int{4}
}

func (x *TripID) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *TripID) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TripID) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        *CartID                `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	OperationType int32                  `protobuf:"varint,2,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	Items         []*Item                `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_rprts_chaika_reports_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_rprts_chaika_reports_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_rprts_chaika_reports_proto_rawDescGZIP(), []int{5}
}

func (x *Cart) GetCartId() *CartID {
	if x != nil {
		return x.CartId
	}
	return nil
}

func (x *Cart) GetOperationType() int32 {
	if x != nil {
		return x.OperationType
	}
	return 0
}

func (x *Cart) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CartID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    string                 `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	OperationTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartID) Reset() {
	*x = CartID{}
	mi := &file_rprts_chaika_reports_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartID) ProtoMessage() {}

func (x *CartID) ProtoReflect() protoreflect.Message {
	mi := &file_rprts_chaika_reports_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartID.ProtoReflect.Descriptor instead.
func (*CartID) Descriptor() ([]byte, []int) {
	return file_rprts_chaika_reports_proto_rawDescGZIP(), []int{6}
}

func (x *CartID) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *CartID) GetOperationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OperationTime
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_rprts_chaika_reports_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_rprts_chaika_reports_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_rprts_chaika_reports_proto_rawDescGZIP(), []int{7}
}

func (x *Item) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Item) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_rprts_chaika_reports_proto protoreflect.FileDescriptor

const file_rprts_chaika_reports_proto_rawDesc = "" +
	"\n" +
	"\x1arprts/chaika_reports.proto\x12\x0echaika_reports\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n" +
	"\x0eGetTripRequest\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\tR\x04year\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"8\n" +
	"\fGetTripReply\x12(\n" +
	"\x04trip\x18\x01 \x01(\v2\x14.chaika_reports.TripR\x04trip\"<\n" +
	"\x04Trip\x124\n" +
	"\bcarriage\x18\x01 \x03(\v2\x18.chaika_reports.CarriageR\bcarriage\"\xbf\x01\n" +
	"\bCarriage\x12/\n" +
	"\atrip_id\x18\x01 \x01(\v2\x16.chaika_reports.TripIDR\x06tripId\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1f\n" +
	"\vcarriage_id\x18\x03 \x01(\x05R\n" +
	"carriageId\x12*\n" +
	"\x05carts\x18\x04 \x03(\v2\x14.chaika_reports.CartR\x05carts\"r\n" +
	"\x06TripID\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\tR\x04year\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"\x8a\x01\n" +
	"\x04Cart\x12/\n" +
	"\acart_id\x18\x01 \x01(\v2\x16.chaika_reports.CartIDR\x06cartId\x12%\n" +
	"\x0eoperation_type\x18\x02 \x01(\x05R\roperationType\x12*\n" +
	"\x05items\x18\x03 \x03(\v2\x14.chaika_reports.ItemR\x05items\"l\n" +
	"\x06CartID\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\tR\n" +
	"employeeId\x12A\n" +
	"\x0eoperation_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\roperationTime\"W\n" +
	"\x04Item\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price2W\n" +
	"\fSalesService\x12G\n" +
	"\aGetTrip\x12\x1e.chaika_reports.GetTripRequest\x1a\x1c.chaika_reports.GetTripReplyB>Z<github.com/yourorg/ChaikaReports/internal/handler/grpc/pb;pbb\x06proto3"

var (
	file_rprts_chaika_reports_proto_rawDescOnce sync.Once
	file_rprts_chaika_reports_proto_rawDescData []byte
)

func file_rprts_chaika_reports_proto_rawDescGZIP() []byte {
	file_rprts_chaika_reports_proto_rawDescOnce.Do(func() {
		file_rprts_chaika_reports_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rprts_chaika_reports_proto_rawDesc), len(file_rprts_chaika_reports_proto_rawDesc)))
	})
	return file_rprts_chaika_reports_proto_rawDescData
}

var file_rprts_chaika_reports_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rprts_chaika_reports_proto_goTypes = []any{
	(*GetTripRequest)(nil),        // 0: chaika_reports.GetTripRequest
	(*GetTripReply)(nil),          // 1: chaika_reports.GetTripReply
	(*Trip)(nil),                  // 2: chaika_reports.Trip
	(*Carriage)(nil),              // 3: chaika_reports.Carriage
	(*TripID)(nil),                // 4: chaika_reports.TripID
	(*Cart)(nil),                  // 5: chaika_reports.Cart
	(*CartID)(nil),                // 6: chaika_reports.CartID
	(*Item)(nil),                  // 7: chaika_reports.Item
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_rprts_chaika_reports_proto_depIdxs = []int32{
	8,  // 0: chaika_reports.GetTripRequest.start_time:type_name -> google.protobuf.Timestamp
	2,  // 1: chaika_reports.GetTripReply.trip:type_name -> chaika_reports.Trip
	3,  // 2: chaika_reports.Trip.carriage:type_name -> chaika_reports.Carriage
	4,  // 3: chaika_reports.Carriage.trip_id:type_name -> chaika_reports.TripID
	8,  // 4: chaika_reports.Carriage.end_time:type_name -> google.protobuf.Timestamp
	5,  // 5: chaika_reports.Carriage.carts:type_name -> chaika_reports.Cart
	8,  // 6: chaika_reports.TripID.start_time:type_name -> google.protobuf.Timestamp
	6,  // 7: chaika_reports.Cart.cart_id:type_name -> chaika_reports.CartID
	7,  // 8: chaika_reports.Cart.items:type_name -> chaika_reports.Item
	8,  // 9: chaika_reports.CartID.operation_time:type_name -> google.protobuf.Timestamp
	0,  // 10: chaika_reports.SalesService.GetTrip:input_type -> chaika_reports.GetTripRequest
	1,  // 11: chaika_reports.SalesService.GetTrip:output_type -> chaika_reports.GetTripReply
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_rprts_chaika_reports_proto_init() }
func file_rprts_chaika_reports_proto_init() {
	if File_rprts_chaika_reports_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rprts_chaika_reports_proto_rawDesc), len(file_rprts_chaika_reports_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rprts_chaika_reports_proto_goTypes,
		DependencyIndexes: file_rprts_chaika_reports_proto_depIdxs,
		MessageInfos:      file_rprts_chaika_reports_proto_msgTypes,
	}.Build()
	File_rprts_chaika_reports_proto = out.File
	file_rprts_chaika_reports_proto_goTypes = nil
	file_rprts_chaika_reports_proto_depIdxs = nil
}
