basePath: /api/v1/report
definitions:
  ChaikaReports_internal_handler_http_schemas.Cart:
    properties:
      cart_id:
        $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.CartID'
      items:
        items:
          $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.Item'
        type: array
      operation_type:
        type: integer
    required:
    - cart_id
    - items
    - operation_type
    type: object
  ChaikaReports_internal_handler_http_schemas.CartID:
    properties:
      employee_id:
        type: string
      operation_time:
        type: string
    required:
    - employee_id
    - operation_time
    type: object
  ChaikaReports_internal_handler_http_schemas.DeleteItemFromCartRequest:
    properties:
      cart_id:
        $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.CartID'
      product_id:
        type: integer
      trip_id:
        $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.TripID'
    required:
    - cart_id
    - product_id
    - trip_id
    type: object
  ChaikaReports_internal_handler_http_schemas.DeleteItemFromCartResponse:
    properties:
      message:
        type: string
    type: object
  ChaikaReports_internal_handler_http_schemas.EmployeeTrip:
    properties:
      employee_id:
        type: string
      end_time:
        type: string
      trip_id:
        $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.TripID'
    type: object
  ChaikaReports_internal_handler_http_schemas.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  ChaikaReports_internal_handler_http_schemas.GetEmployeeCartsInTripPagedResponse:
    properties:
      carts:
        items:
          $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.Cart'
        type: array
      next_cursor:
        description: '"" means no more carts'
        type: string
    type: object
  ChaikaReports_internal_handler_http_schemas.GetEmployeeCartsInTripResponse:
    properties:
      carts:
        items:
          $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.Cart'
        type: array
    type: object
  ChaikaReports_internal_handler_http_schemas.GetEmployeeIDsByTripResponse:
    properties:
      employee_ids:
        items:
          type: string
        type: array
    type: object
  ChaikaReports_internal_handler_http_schemas.GetEmployeeTripsResponse:
    properties:
      employee_trips:
        items:
          $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.EmployeeTrip'
        type: array
    required:
    - employee_trips
    type: object
  ChaikaReports_internal_handler_http_schemas.InsertSalesRequest:
    properties:
      carriage_id:
        type: integer
      carts:
        items:
          $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.Cart'
        type: array
      end_time:
        type: string
      trip_id:
        $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.TripID'
    required:
    - carriage_id
    - carts
    - end_time
    - trip_id
    type: object
  ChaikaReports_internal_handler_http_schemas.InsertSalesResponse:
    properties:
      message:
        type: string
    type: object
  ChaikaReports_internal_handler_http_schemas.Item:
    properties:
      price:
        description: Storing price in kopeeks
        minimum: 0
        type: integer
      product_id:
        type: integer
      quantity:
        type: integer
    required:
    - price
    - product_id
    - quantity
    type: object
  ChaikaReports_internal_handler_http_schemas.TripID:
    properties:
      route_id:
        type: string
      start_time:
        type: string
      year:
        type: string
    required:
    - route_id
    - start_time
    - year
    type: object
  ChaikaReports_internal_handler_http_schemas.UpdateItemQuantityRequest:
    properties:
      cart_id:
        $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.CartID'
      new_quantity:
        type: integer
      product_id:
        type: integer
      trip_id:
        $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.TripID'
    required:
    - cart_id
    - new_quantity
    - product_id
    - trip_id
    type: object
  ChaikaReports_internal_handler_http_schemas.UpdateItemQuantityResponse:
    properties:
      message:
        type: string
    type: object
host: chaika-soft.ru
info:
  contact:
    email: support@chaikareports.com
    name: API Support
    url: http://www.swagger.io/support
  description: API documentation for the ChaikaReports microservice.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: ChaikaReports API
  version: 1.0.8
paths:
  /sale:
    post:
      consumes:
      - application/json
      description: Inserts sales data into the system.
      parameters:
      - description: Insert Sales Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.InsertSalesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Data inserted successfully
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.InsertSalesResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.ErrorResponse'
      summary: Insert Sales Data
      tags:
      - Sales
  /trip/cart/employee:
    get:
      consumes:
      - application/json
      description: Returns all carts handled by a specific employee during a specific
        trip.
      parameters:
      - description: Route ID
        in: query
        name: route_id
        required: true
        type: string
      - description: Year
        in: query
        name: year
        required: true
        type: string
      - description: Trip Start Time in RFC3339 format
        in: query
        name: start_time
        required: true
        type: string
      - description: Employee ID
        in: query
        name: employee_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.GetEmployeeCartsInTripResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.ErrorResponse'
      summary: Get Employee Carts in Trip
      tags:
      - Sales
  /trip/cart/employee/paged:
    get:
      consumes:
      - application/json
      description: Returns complete carts, paginated by carts with an opaque cursor.
      parameters:
      - description: Route ID
        in: query
        name: route_id
        required: true
        type: string
      - description: Year
        in: query
        name: year
        required: true
        type: string
      - description: Trip Start Time (RFC3339)
        in: query
        name: start_time
        required: true
        type: string
      - description: Employee ID
        in: query
        name: employee_id
        required: true
        type: string
      - description: Number of complete carts to return (default 10)
        in: query
        name: limit
        type: integer
      - description: Opaque cursor from previous response; empty to start
        in: query
        name: cursor
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.GetEmployeeCartsInTripPagedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.ErrorResponse'
      summary: Get Employee Carts in Trip (paged, cart-safe)
      tags:
      - Sales
  /trip/cart/item:
    delete:
      consumes:
      - application/json
      description: Deletes a product from a specific cart.
      parameters:
      - description: Delete Item from Cart Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.DeleteItemFromCartRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.DeleteItemFromCartResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.ErrorResponse'
      summary: Delete Item from Cart
      tags:
      - Sales
  /trip/cart/item/quantity:
    put:
      consumes:
      - application/json
      description: Updates the quantity of a specific product in a cart.
      parameters:
      - description: Update Item Quantity Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.UpdateItemQuantityRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.UpdateItemQuantityResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.ErrorResponse'
      summary: Update Item Quantity
      tags:
      - Sales
  /trip/employee_id:
    get:
      consumes:
      - application/json
      description: Returns all employee IDs who worked during a specific trip.
      parameters:
      - description: Route ID
        in: query
        name: route_id
        required: true
        type: string
      - description: Year
        in: query
        name: year
        required: true
        type: string
      - description: Trip Start Time in RFC3339 format
        in: query
        name: start_time
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.GetEmployeeIDsByTripResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.ErrorResponse'
      summary: Get Employee IDs by Trip
      tags:
      - Sales
  /trip/employee_trip:
    get:
      consumes:
      - application/json
      description: Returns all trips completed by an employee during a year.
      parameters:
      - description: Employee ID
        in: query
        name: employee_id
        required: true
        type: string
      - description: Year
        in: query
        name: year
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.GetEmployeeTripsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ChaikaReports_internal_handler_http_schemas.ErrorResponse'
      summary: Get Employee Trips
      tags:
      - Sales
swagger: "2.0"
