name: Deploy ChaikaReports image

on:
  workflow_run:
    workflows:
      - 'Go CI/CD Pipeline'
    branches:
      - 'master'
    types:
      - 'completed'

jobs:
  checkout:
    name: Checkout code and check ver
    runs-on: ubuntu-latest
    outputs:
      version_modified: ${{ steps.check-version.outputs.version_modified }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if version was modified
        id: check-version
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "version"; then
              echo "version_modified=true" >> $GITHUB_OUTPUT
          else
              echo "version_modified=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    name: Push new image into registry
    runs-on: ubuntu-latest
    needs: checkout
    if: ${{github.event.workflow_run.conclusion == 'success' && needs.checkout.outputs.version_modified == 'true'}}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: harbor.remystorage.ru
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Read version from file
        id: version
        run: |
          VERSION=$(cat version | tr -d ' \n')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: harbor.remystorage.ru/chaika/chaika-reports:${{ env.VERSION }}
          file: ./Dockerfile
